/** Major Pakistan cities for registration (datalist + free-text). */
export const PAKISTAN_CITIES = [
  'Abbottabad',
  'Attock',
  'Bahawalpur',
  'Bannu',
  'Chiniot',
  'Dera Ghazi Khan',
  'Faisalabad',
  'Gilgit',
  'Gujranwala',
  'Gujrat',
  'Hyderabad',
  'Islamabad',
  'Jhang',
  'Karachi',
  'Kasur',
  'Khanewal',
  'Lahore',
  'Larkana',
  'Mardan',
  'Multan',
  'Muzaffarabad',
  'Nawabshah',
  'Okara',
  'Peshawar',
  'Quetta',
  'Rawalpindi',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Sukkur',
  'Swat',
];
