export const ROLES = {
  COMPANY_OWNER: 'COMPANY_OWNER',
  BRANCH_OWNER: 'BRANCH_OWNER',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  TECHNICIAN: 'TECHNICIAN',
  CUSTOMER: 'CUSTOMER',
};

export const normalizeRole = (role) => (role === 'MANAGER' ? ROLES.BRANCH_MANAGER : role);

export const BRANCH_DASHBOARD_ROLES = [
  ROLES.COMPANY_OWNER,
  ROLES.BRANCH_OWNER,
  ROLES.BRANCH_MANAGER,
  ROLES.EMPLOYEE,
  ROLES.TECHNICIAN,
];
